In [2]:
import sys
import os

project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
print(project_root)
if project_root not in sys.path:
    sys.path.append(project_root)

c:\Users\Camille\Documents\TWR

In [3]:
from app.config.container import campaign_service, request_service

c:\Users\Camille\Documents\TWR\deep_agents_twr\.venv\Lib\site-packages\motor\core.py:171: UserWarning: You appear to be connected to a DocumentDB cluster. For more information regarding feature compatibility and support please visit https://www.mongodb.com/supportability/documentdb
  delegate = self.__delegate_class__(*args, **kwargs)

Garantindo índices...

In [4]:
traffic_sources = [
      "google",
      "tiktok",
      # "taboola",
      "facebook",
]

configs = [
      "fasttext",
]

In [5]:
import pandas as pd
%reload_ext autoreload
%autoreload 2
from app.services.attetion_mil_article import MILAttetionService

for source in traffic_sources:
      for emb_config in configs:

            hashes = await campaign_service.fetch_recent_active_campaigns(
                  traffic_source=source,
                  limit=150
            )

            requests = await request_service.fetch_training_sample_by_hashes(
                  hashes=hashes,
                  limit_each=10000
            )

            hashes_test = await campaign_service.fetch_recent_active_campaign_hashes_excluding(
                  excluded_hashes=hashes,
                  traffic_source=source
            )

            teste = await request_service.fetch_training_sample_by_hashes(
                  hashes=hashes_test,
                  limit_each=1000
            )

            data = pd.DataFrame(requests)
            data_teste = pd.DataFrame(teste)

            model_service = MILAttetionService(
                  traffic_source=source,
                  emb_config=emb_config
            )

            model = model_service.train_bags_accumulated(
                  data=data,
                  epochs=15,
                  accumulation_steps=64
            )

            df_result = model_service.predict(data_teste)

            display(df_result)

Local file already updated: fasttext_google.model
Local file already updated: fasttext_google.model.syn1neg.npy
Local file already updated: fasttext_google.model.wv.vectors_ngrams.npy
Local file already updated: fasttext_google.model.wv.vectors_vocab.npy
[INFO] FastText model não encontrado em models/google/fasttext_google.model. Tentando buscar do S3...
[DEBUG] Model Path FASTTEXT: models/google/fasttext_google.model
Modelo last modified no s3:  2026-03-04 18:28:53+00:00
Local file already updated
Enter to Fasttext encoder

Criando Vocabulário: 100%|██████████| 18194/18194 [00:10<00:00, 1754.09it/s]

Using 11 out of 12 cores

Vetorizando: 100%|██████████| 18194/18194 [05:38<00:00, 53.70it/s]

Finishing encoding
Total de Bags Processadas: 9185
  -> Bags Positivas (com bots): 3026
  -> Bags Negativas (seguras): 6159

Epoch 1/15: 100%|██████████| 9185/9185 [01:31<00:00, 100.87it/s, loss=0.6071, acc=0.6903]

End of epoch 1 | Mean Loss: 0.6071

Epoch 2/15: 100%|██████████| 9185/9185 [01:30<00:00, 101.02it/s, loss=0.5254, acc=0.7734]

End of epoch 2 | Mean Loss: 0.5254

Epoch 3/15: 100%|██████████| 9185/9185 [01:26<00:00, 106.10it/s, loss=0.4865, acc=0.7930]

End of epoch 3 | Mean Loss: 0.4865

Epoch 4/15: 100%|██████████| 9185/9185 [00:41<00:00, 223.46it/s, loss=0.4665, acc=0.8048]

End of epoch 4 | Mean Loss: 0.4665

Epoch 5/15: 100%|██████████| 9185/9185 [00:43<00:00, 212.97it/s, loss=0.4500, acc=0.8156]

End of epoch 5 | Mean Loss: 0.4500

Epoch 6/15: 100%|██████████| 9185/9185 [01:25<00:00, 107.24it/s, loss=0.4391, acc=0.8251]

End of epoch 6 | Mean Loss: 0.4391

Epoch 7/15: 100%|██████████| 9185/9185 [00:59<00:00, 153.34it/s, loss=0.4306, acc=0.8305]

End of epoch 7 | Mean Loss: 0.4306

Epoch 8/15: 100%|██████████| 9185/9185 [00:34<00:00, 262.69it/s, loss=0.4232, acc=0.8364]

End of epoch 8 | Mean Loss: 0.4232

Epoch 9/15: 100%|██████████| 9185/9185 [00:35<00:00, 257.64it/s, loss=0.4207, acc=0.8389]

End of epoch 9 | Mean Loss: 0.4207

Epoch 10/15: 100%|██████████| 9185/9185 [00:33<00:00, 276.22it/s, loss=0.4178, acc=0.8417]

End of epoch 10 | Mean Loss: 0.4178

Epoch 11/15: 100%|██████████| 9185/9185 [00:35<00:00, 262.32it/s, loss=0.4092, acc=0.8445]

End of epoch 11 | Mean Loss: 0.4092

Epoch 12/15: 100%|██████████| 9185/9185 [00:37<00:00, 243.08it/s, loss=0.4093, acc=0.8462]

End of epoch 12 | Mean Loss: 0.4093

Epoch 13/15: 100%|██████████| 9185/9185 [00:52<00:00, 173.87it/s, loss=0.4055, acc=0.8463]

End of epoch 13 | Mean Loss: 0.4055

Epoch 14/15: 100%|██████████| 9185/9185 [01:29<00:00, 102.29it/s, loss=0.3985, acc=0.8496]

End of epoch 14 | Mean Loss: 0.3985

Epoch 15/15: 100%|██████████| 9185/9185 [01:19<00:00, 116.22it/s, loss=0.3978, acc=0.8498]

End of epoch 15 | Mean Loss: 0.3978
Salving model at:  models/google/fasttext/attention_mil_bundle.pth
Deploy done successfuly
Enter to Fasttext encoder

Criando Vocabulário: 100%|██████████| 2000/2000 [00:00<00:00, 2783.62it/s]

Using 11 out of 12 cores

Vetorizando: 100%|██████████| 2000/2000 [00:14<00:00, 138.88it/s]

Finishing encoding

,bag_id,embedding,decision_mil,headers,request,ip,mil_bot_probability,mil_prediction,attention_weight
0,"100.55.35.0/24 | amazon.com, inc.","[0.03389877, 0.17567497, -0.13787073, -0.01914...",1,"{""Host"":""www.karwspoks.store"",""X-Request-Id"":""...",[],100.55.35.25,0.999645,1,1.000000
1,103.7.205.0/24 | community fibre limited,"[0.07085987, 0.02407394, -0.048238453, -0.0006...",1,"{""Host"":""oficial.vidanatural25.online"",""X-Requ...",[],103.7.205.15,0.954284,1,1.000000
2,104.164.121.0/24 | egihosting,"[0.053298753, 0.081961915, -0.087067045, -0.00...",1,"{""Host"":""www.kratchequi.store"",""X-Request-Id"":...",[],104.164.121.162,0.992635,1,1.000000
3,104.237.188.0/24 | google llc,"[0.015192097, 0.183027, -0.040166315, 0.004023...",1,"{""Host"":""oficial.vidanatural25.online"",""X-Requ...","{""utm_source"":""google"",""utm_campaign"":""2359149...",104.237.188.9,0.263013,0,1.000000
4,104.237.189.0/24 | google llc,"[-0.0008807339, 0.16678742, -0.058882974, -0.0...",1,"{""Host"":""oficial.vidanatural25.online"",""X-Requ...","{""utm_source"":""google"",""utm_campaign"":""2360186...",104.237.189.12,0.675349,1,0.999986
...,...,...,...,...,...,...,...,...,...
1995,94.230.145.0/24 | airwaynet i,"[0.07051241, 0.040357318, -0.00018461511, -0.0...",1,"{""Host"":""www.kratchequi.store"",""X-Request-Id"":...","{""cr"":""795792536538"",""plc"":"""",""mtx"":"""",""rdn"":""...",94.230.145.71,0.098752,0,0.669294
1996,94.230.145.0/24 | airwaynet i,"[0.069780685, 0.040976793, -0.0010153803, -0.0...",0,"{""Host"":""www.kratchequi.store"",""X-Request-Id"":...","{""cr"":""795792536538"",""plc"":"""",""mtx"":"""",""rdn"":""...",94.230.145.216,0.098752,0,0.330706
1997,"94.230.156.0/24 | airwaynet, a.s.","[0.062411185, 0.024256008, -0.016286109, -0.02...",0,"{""Host"":""www.kratchequi.store"",""X-Request-Id"":...","{""cr"":""797853842581"",""plc"":"""",""mtx"":"""",""rdn"":""...",94.230.156.139,0.165819,0,1.000000
1998,95.173.83.0/24 | ha-vel internet s.r.o.,"[0.060975626, 0.013351867, -0.031471465, 0.005...",1,"{""Host"":""www.kratchequi.store"",""X-Request-Id"":...","{""cr"":""795792536538"",""plc"":"""",""mtx"":"""",""rdn"":""...",95.173.83.22,0.167204,0,1.000000
1999,"95.82.141.0/24 | o2 czech republic, a.s.","[0.056671202, 0.034304246, -0.016695328, -0.00...",0,"{""Host"":""www.kratchequi.store"",""X-Request-Id"":...","{""cr"":""797963969214"",""plc"":"""",""mtx"":"""",""rdn"":""...",95.82.141.36,0.181613,0,1.000000

Local file already updated: fasttext_tiktok.model
Local file already updated: fasttext_tiktok.model.syn1neg.npy
Local file already updated: fasttext_tiktok.model.wv.vectors_ngrams.npy
Local file already updated: fasttext_tiktok.model.wv.vectors_vocab.npy
Modelo last modified no s3:  2026-03-04 18:40:13+00:00
Updating model from s3: MIL/tiktok/fasttext/prod/2026-03-04_15-40.pth -> models/tiktok/fasttext/attention_mil_bundle.pth
Enter to Fasttext encoder

Criando Vocabulário: 100%|██████████| 20000/20000 [00:22<00:00, 880.87it/s]

Using 11 out of 12 cores

Vetorizando: 100%|██████████| 20000/20000 [03:27<00:00, 96.17it/s]

Finishing encoding
Total de Bags Processadas: 13679
  -> Bags Positivas (com bots): 5689
  -> Bags Negativas (seguras): 7990

Epoch 1/15: 100%|██████████| 13679/13679 [01:27<00:00, 157.16it/s, loss=0.5782, acc=0.6879]

End of epoch 1 | Mean Loss: 0.5782

Epoch 2/15: 100%|██████████| 13679/13679 [01:05<00:00, 209.87it/s, loss=0.4987, acc=0.7626]

End of epoch 2 | Mean Loss: 0.4987

Epoch 3/15: 100%|██████████| 13679/13679 [00:55<00:00, 247.88it/s, loss=0.4729, acc=0.7800]

End of epoch 3 | Mean Loss: 0.4729

Epoch 4/15: 100%|██████████| 13679/13679 [01:16<00:00, 179.06it/s, loss=0.4519, acc=0.7972]

End of epoch 4 | Mean Loss: 0.4519

Epoch 5/15: 100%|██████████| 13679/13679 [01:16<00:00, 178.36it/s, loss=0.4272, acc=0.8118]

End of epoch 5 | Mean Loss: 0.4272

Epoch 6/15: 100%|██████████| 13679/13679 [00:53<00:00, 254.60it/s, loss=0.4062, acc=0.8245]

End of epoch 6 | Mean Loss: 0.4062

Epoch 7/15: 100%|██████████| 13679/13679 [01:37<00:00, 140.29it/s, loss=0.3917, acc=0.8318]

End of epoch 7 | Mean Loss: 0.3917

Epoch 8/15: 100%|██████████| 13679/13679 [01:38<00:00, 139.14it/s, loss=0.3745, acc=0.8422]

End of epoch 8 | Mean Loss: 0.3745

Epoch 9/15: 100%|██████████| 13679/13679 [00:53<00:00, 255.03it/s, loss=0.3582, acc=0.8524]

End of epoch 9 | Mean Loss: 0.3582

Epoch 10/15: 100%|██████████| 13679/13679 [00:51<00:00, 268.00it/s, loss=0.3480, acc=0.8562]

End of epoch 10 | Mean Loss: 0.3480

Epoch 11/15: 100%|██████████| 13679/13679 [00:53<00:00, 257.25it/s, loss=0.3349, acc=0.8630]

End of epoch 11 | Mean Loss: 0.3349

Epoch 12/15: 100%|██████████| 13679/13679 [01:24<00:00, 162.76it/s, loss=0.3269, acc=0.8663]

End of epoch 12 | Mean Loss: 0.3269

Epoch 13/15: 100%|██████████| 13679/13679 [01:33<00:00, 146.71it/s, loss=0.3201, acc=0.8684]

End of epoch 13 | Mean Loss: 0.3201

Epoch 14/15: 100%|██████████| 13679/13679 [01:17<00:00, 176.37it/s, loss=0.3149, acc=0.8714]

End of epoch 14 | Mean Loss: 0.3149

Epoch 15/15: 100%|██████████| 13679/13679 [01:05<00:00, 207.64it/s, loss=0.3036, acc=0.8769]

End of epoch 15 | Mean Loss: 0.3036
Salving model at:  models/tiktok/fasttext/attention_mil_bundle.pth
Deploy done successfuly
Enter to Fasttext encoder

Criando Vocabulário: 100%|██████████| 2000/2000 [00:01<00:00, 1122.76it/s]

Using 11 out of 12 cores

Vetorizando: 100%|██████████| 2000/2000 [00:35<00:00, 56.24it/s]

Finishing encoding

,bag_id,embedding,decision_mil,headers,request,ip,mil_bot_probability,mil_prediction,attention_weight
0,100.14.145.0/24 | verizon communications,"[0.06299644, 0.06494691, -0.041114785, -0.0002...",1,"{""Host"":""lp.vitalitymens.site"",""X-Request-Id"":...","{""src"":""10050001"",""sku"":""TikTok"",""ttclid"":""E_C...",100.14.145.140,0.404352,0,1.0
1,100.26.150.0/24 | amazon.com,"[0.011334581, 0.19171336, -0.08029118, -0.0013...",1,"{""Host"":""lp.mensenergy.site"",""X-Request-Id"":""6...","{""src"":""11233001"",""sku"":""TikTok"",""ttclid"":""E_C...",100.26.150.104,0.747781,1,1.0
2,100.34.63.0/24 | verizon communications,"[0.066458866, 0.04937401, -0.039915804, 0.0064...",1,"{""Host"":""tw.cortgela.online"",""X-Request-Id"":""6...","{""src"":""10050001"",""sku"":""TikTok"",""ttclid"":""E_C...",100.34.63.19,0.507192,1,1.0
3,100.37.105.0/24 | verizon communications,"[0.06837005, 0.06239022, -0.039136, -0.0022910...",1,"{""Host"":""lp.vitalitymens.site"",""X-Request-Id"":...","{""src"":""10050001"",""sku"":""TikTok"",""ttclid"":""E_C...",100.37.105.194,0.405869,0,1.0
4,100.37.39.0/24 | verizon communications,"[0.048493553, 0.08559841, -0.044226225, 0.0031...",0,"{""Host"":""lp.mensenergy.site"",""X-Request-Id"":""6...","{""src"":""11233001"",""sku"":""TikTok"",""ttclid"":""E_C...",100.37.39.141,0.210319,0,1.0
...,...,...,...,...,...,...,...,...,...
1995,"99.125.82.0/24 | at&t enterprises, llc","[0.0517973, 0.112784624, -0.032058056, 0.00830...",0,"{""Host"":""lp.mensenergy.site"",""X-Request-Id"":""7...","{""src"":""11233001"",""sku"":""TikTok"",""ttclid"":""E_C...",99.125.82.189,0.337485,0,1.0
1996,"99.137.144.0/24 | at&t enterprises, llc","[0.05784456, 0.09556299, -0.036862735, 0.01543...",1,"{""Host"":""tw.cortgela.online"",""X-Request-Id"":""8...","{""src"":""10050001"",""sku"":""TikTok"",""ttclid"":""E_C...",99.137.144.93,0.656693,1,1.0
1997,"99.24.22.0/24 | at&t enterprises, llc","[0.052743234, 0.11144636, -0.039079748, 0.0059...",1,"{""Host"":""lp.vitalitymens.site"",""X-Request-Id"":...","{""src"":""10050001"",""sku"":""TikTok"",""ttclid"":""E_C...",99.24.22.184,0.556053,1,1.0
1998,"99.47.185.0/24 | at&t enterprises, llc","[0.055326153, 0.110298604, -0.037363015, 0.005...",1,"{""Host"":""lp.vitalitymens.site"",""X-Request-Id"":...","{""src"":""10050001"",""sku"":""TikTok"",""ttclid"":""E_C...",99.47.185.88,0.632048,1,1.0
1999,"99.63.68.0/24 | at&t enterprises, llc","[0.055493668, 0.09249447, -0.036791842, 0.0123...",1,"{""Host"":""lp.vitalitymens.site"",""X-Request-Id"":...","{""src"":""10050001"",""sku"":""TikTok"",""ttclid"":""E_C...",99.63.68.67,0.554894,1,1.0

CancelledError:

In [ ]:
df_result[(df_result["decision_mil"] == 0) & (df_result["mil_prediction"] == 1)]["attention_weight"].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
df_result[(df_result["decision_mil"] == 0) & (df_result["mil_prediction"] == 0)]["attention_weight"].value_counts()

attention_weight
1.000000    532
0.500000     26
0.249869      3
0.200772      3
0.500061      2
           ...
0.330798      1
0.330900      1
0.338302      1
0.501634      1
0.498366      1
Name: count, Length: 72, dtype: int64

In [ ]:
df_result["decision_mil"].value_counts()

decision_mil
0    635
1    635
Name: count, dtype: int64

In [ ]:
df_result["mil_prediction"].value_counts()

mil_prediction
0    1270
Name: count, dtype: int64

In [ ]:
from sklearn.metrics import classification_report


matriz_bag_instance = pd.crosstab(
    df_result['decision_mil'], 
    df_result['mil_prediction'], 
    rownames=['Real (Bag: 0=Segura, 1=Bot)'], 
    colnames=['Previsão do Modelo']
)

print("=== MATRIZ DE CONFUSÃO (NÍVEL DA BAG) ===\n")
display(matriz_bag_instance)

# 3. Exibe as Métricas Avançadas (Precisão, Recall, F1-Score)
print("\n=== RELATÓRIO DE MÉTRICAS (NÍVEL DA INSTÂNCIA) ===")
print(classification_report(df_result['decision_mil'], df_result['mil_prediction']))

=== MATRIZ DE CONFUSÃO (NÍVEL DA BAG) ===

Previsão do Modelo             0
Real (Bag: 0=Segura, 1=Bot)
0                            635
1                            635

=== RELATÓRIO DE MÉTRICAS (NÍVEL DA INSTÂNCIA) ===
              precision    recall  f1-score   support

           0       0.50      1.00      0.67       635
           1       0.00      0.00      0.00       635

    accuracy                           0.50      1270
   macro avg       0.25      0.50      0.33      1270
weighted avg       0.25      0.50      0.33      1270

c:\Users\Camille\Documents\TWR\deep_agents_twr\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Camille\Documents\TWR\deep_agents_twr\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Camille\Documents\TWR\deep_agents_twr\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [ ]:

# 1. Comprime os dados de volta para 1 linha por Bag
bag_level_df = df_result.groupby('bag_id').agg(
    bag_true_label=('decision_mil', 'max'),     # Se tem pelo menos um bot (1), a bag é bot (1)
    bag_prediction=('mil_prediction', 'first')  # A previsão do modelo para aquela bag
).reset_index()

# 2. Cria a Matriz de Confusão
matriz_bag = pd.crosstab(
    bag_level_df['bag_true_label'], 
    bag_level_df['bag_prediction'], 
    rownames=['Real (Bag: 0=Segura, 1=Bot)'], 
    colnames=['Previsão do Modelo']
)

print("=== MATRIZ DE CONFUSÃO (NÍVEL DA BAG) ===\n")
display(matriz_bag)

# 3. Exibe as Métricas Avançadas (Precisão, Recall, F1-Score)
print("\n=== RELATÓRIO DE MÉTRICAS (NÍVEL DA BAG) ===")
print(classification_report(bag_level_df['bag_true_label'], bag_level_df['bag_prediction']))

=== MATRIZ DE CONFUSÃO (NÍVEL DA BAG) ===

Previsão do Modelo             0
Real (Bag: 0=Segura, 1=Bot)
0                            575
1                             25

=== RELATÓRIO DE MÉTRICAS (NÍVEL DA BAG) ===
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       575
           1       0.00      0.00      0.00        25

    accuracy                           0.96       600
   macro avg       0.48      0.50      0.49       600
weighted avg       0.92      0.96      0.94       600

c:\Users\Camille\Documents\TWR\deep_agents_twr\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Camille\Documents\TWR\deep_agents_twr\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Camille\Documents\TWR\deep_agents_twr\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [ ]:
# Analisando as probabilidades brutas (antes de virarem 0 ou 1)
resumo_probabilidades = bag_level_df.merge(
    df_result[['bag_id', 'mil_bot_probability']].drop_duplicates(), 
    on='bag_id'
)

print("=== DISTRIBUIÇÃO DE PROBABILIDADE POR CLASSE REAL ===")
display(resumo_probabilidades.groupby('bag_true_label')['mil_bot_probability'].describe()[['mean', 'min', '50%', 'max']])

=== DISTRIBUIÇÃO DE PROBABILIDADE POR CLASSE REAL ===

                    mean       min       50%       max
bag_true_label
0               0.356227  0.350251  0.356110  0.363023
1               0.362420  0.355565  0.363575  0.366587