In [1]:
import sys
import os

project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
print(project_root)
if project_root not in sys.path:
    sys.path.append(project_root)

c:\Users\Camille\Documents\TWR\deep_agents_twr

In [2]:
def exctract_user_agent(headers):
      ua = headers.get("user-agent")
      return ua

In [3]:
traffic_sources = [
      # "google",
      "facebook",
      "tiktok",
      "outbrain"
]

In [4]:
# %reload_ext autoreload
# %autoreload 2

# import pandas as pd
# from app.config.container import campaign_service, request_service
# from sentence_transformers import SentenceTransformer
# from tests.request_clustering_service import RequestClusteringPipeline
# from app.utils.analise import parse_dict_col

# results = {}
# for source in traffic_sources:
    
#     hashes = await campaign_service.fetch_recent_active_campaigns(
#           traffic_source=source,
#           limit=10
#     )
#     # hashes = ["9xvp496ldw"]

#     print(len(hashes))
#     print(hashes)

#     hashes = ["vbpfqcjnvm"]

#     requests = await request_service.fetch_training_sample_by_hashes(
#         hashes=hashes,
#         limit_each=1000,
#         only_rule_id=False
#     )

#     data = pd.DataFrame(requests)
#     print(data.head())
#     data['headers'] = data['headers'].apply(parse_dict_col)
#     data['request'] = data['request'].apply(parse_dict_col)

#     data["ua"] = data["headers"].apply(exctract_user_agent)
#     print(data.head())

#     model = SentenceTransformer('all-MiniLM-L6-v2') 

#     pipeline = RequestClusteringPipeline(
#         embedding_model=model,
#         max_header_freq=0.7,
#         min_cluster_size=30
#     )
    

#     df_result = pipeline.run(data)
#     print(f"--- Results Clsutering for {source} ---")
#     print(df_result["classification"].value_counts())
#     results[source] = df_result

In [ ]:
import pandas as pd
from sentence_transformers import SentenceTransformer

from app.config.container import request_service
from app.utils.analise import parse_dict_col
from tests.request_clustering_service import RequestClusteringPipeline


hashes = ["g1dg9qeh5m"]

requests = await request_service.fetch_training_sample_by_hashes(
      hashes=hashes,
      limit_each=1000,
      only_rule_id=False
)

data = pd.DataFrame(requests)
print(data.head())
data['headers'] = data['headers'].apply(parse_dict_col)
data['request'] = data['request'].apply(parse_dict_col)

data["ua"] = data["headers"].apply(exctract_user_agent)
print(data.head())

model = SentenceTransformer('all-MiniLM-L6-v2') 

pipeline = RequestClusteringPipeline(
      embedding_model=model,
      max_header_freq=0.7,
      min_cluster_size=30
)


df_result = pipeline.run(data)
print(f"--- Results Clsutering for {hashes} ---")
print(df_result["classification"].value_counts())

c:\Users\Camille\Documents\TWR\deep_agents_twr\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\Camille\Documents\TWR\deep_agents_twr\.venv\Lib\site-packages\motor\core.py:171: UserWarning: You appear to be connected to a DocumentDB cluster. For more information regarding feature compatibility and support please visit https://www.mongodb.com/supportability/documentdb
  delegate = self.__delegate_class__(*args, **kwargs)

Garantindo índices...
                 datetime decision  \
0 2026-03-09 20:11:36.084     bots
1 2026-03-09 20:11:32.688     bots
2 2026-03-09 20:11:05.399     bots
3 2026-03-09 20:11:02.257     bots
4 2026-03-09 20:11:00.157     bots

                                             headers  \
0  {"Host":"www.viveremforma.site","X-Request-Id"...
1  {"Host":"www.viveremforma.site","X-Request-Id"...
2  {"Host":"www.viveremforma.site","X-Request-Id"...
3  {"Host":"www.viveremforma.site","X-Request-Id"...
4  {"Host":"www.viveremforma.site","X-Request-Id"...

                                       ip  \
0   2804:14d:884:8f4c:8e2c:c092:7b00:8b8d
1                          177.44.171.180
2                          177.44.171.180
3  2804:868:d045:fda1:21c3:a93c:604d:3bc6
4                          177.44.171.180

                                   ip_api_isp  \
0             claro nxt telecomunicacoes ltda
1      wiip telecom serviÇos de internet ltda
2      wiip telecom serviÇos de internet ltda
3  desktop sigmanet comunicação multimídia sa
4      wiip telecom serviÇos de internet ltda

                                             request
0  {"CampaignID":"535950693","CreativeID":"535951...
1  {"CampaignID":"535953195","CreativeID":"535953...
2  {"CampaignID":"535953195","CreativeID":"535953...
3  {"CampaignID":"538067941","CreativeID":"538068...
4  {"CampaignID":"535953195","CreativeID":"535953...
                 datetime decision  \
0 2026-03-09 20:11:36.084     bots
1 2026-03-09 20:11:32.688     bots
2 2026-03-09 20:11:05.399     bots
3 2026-03-09 20:11:02.257     bots
4 2026-03-09 20:11:00.157     bots

                                             headers  \
0  {'Host': 'www.viveremforma.site', 'X-Request-I...
1  {'Host': 'www.viveremforma.site', 'X-Request-I...
2  {'Host': 'www.viveremforma.site', 'X-Request-I...
3  {'Host': 'www.viveremforma.site', 'X-Request-I...
4  {'Host': 'www.viveremforma.site', 'X-Request-I...

                                       ip  \
0   2804:14d:884:8f4c:8e2c:c092:7b00:8b8d
1                          177.44.171.180
2                          177.44.171.180
3  2804:868:d045:fda1:21c3:a93c:604d:3bc6
4                          177.44.171.180

                                   ip_api_isp  \
0             claro nxt telecomunicacoes ltda
1      wiip telecom serviÇos de internet ltda
2      wiip telecom serviÇos de internet ltda
3  desktop sigmanet comunicação multimídia sa
4      wiip telecom serviÇos de internet ltda

                                             request    ua
0  {'CampaignID': '535950693', 'CreativeID': '535...  None
1  {'CampaignID': '535953195', 'CreativeID': '535...  None
2  {'CampaignID': '535953195', 'CreativeID': '535...  None
3  {'CampaignID': '538067941', 'CreativeID': '538...  None
4  {'CampaignID': '535953195', 'CreativeID': '535...  None

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3288.52it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

2. Serializando requisições e gerando embeddings...
1. Calculando cardinalidade e filtrando headers...
   -> Headers mantidos (76): {'Accept-Language', 'X-Body-Hc', 'Ip-Api-Proxy', 'X-Http-Version', 'Ip-Api-City', 'Cf-Region', 'Sec-Fetch-Mode', 'Cf-Ipcountry', 'Cf-Postal-Code', 'Cf-Region-Code', 'Cdn-Loop', 'Cf-Iplongitude', 'X-Threat-Score', 'X-Body-Scr', 'Sec-Gpc', 'Cf-Ipcontinent', 'X-Verified-Bot-Category', 'X-Body-Touch', 'If-Modified-Since', 'Sec-Fetch-Site', 'Save-Data', 'X-Asn', 'Accept', 'X-Forwarded-Scheme', 'Accept-Encoding', 'Cf-Timezone', 'Sec-Ch-Ua-Mobile', 'X-Body-Pluginslength', 'Dnt', 'X-Body-Lang', 'Sec-Fetch-Dest', 'X-Body-Wd', 'X-Body-Pdfviewerenabled', 'Forwarded', 'Ip-Api-Isp', 'Upgrade-Insecure-Requests', 'X-Client-Bot', 'X-Body-Suspres', 'Ip-Api-Region-Name', 'Cf-Cert-Verified', 'X-Forwarded-Proto', 'Ip-Api-Hosting', 'Sec-Ch-Ua', 'Cookie', 'Host', 'X-Body-Vis', 'Ip-Api-As', 'Cache-Control', 'Ip-Api-Zip', 'Cf-Ipcity', 'Cf-Cert-Revoked', 'Ip-Api-Reverse', 'Priority', 'X-Body-Platform', 'X-Body-Tz', 'From', 'Sec-Ch-Ua-Platform', 'X-Body-Ua', 'User-Agent', 'Cf-Cert-Presented', 'X-Http-Tls-Version', 'Pragma', 'X-Forwarded-Host', 'Cf-Visitor', 'X-Http-Ssl-Protocol', 'X-Requested-With', 'X-Scheme', 'X-Http-Method', 'X-Body-Langs', 'X-Body-Dm', 'Ip-Api-Org', 'X-Forwarded-Port', 'Cf-Metro-Code', 'Origin', 'Cf-Iplatitude', 'Ip-Api-Asname'}
   -> Gerando embeddings RAW...

Batches: 100%|██████████| 32/32 [00:23<00:00,  1.38it/s]

   -> Gerando embeddings FILTERED...

Batches: 100%|██████████| 32/32 [00:22<00:00,  1.43it/s]

3. Aplicando t-SNE (Redução de dimensionalidade)...
4. Clusterizando com HDBSCAN e classificando...
5. Gerando visualizações 3D...

Pipeline finalizado com sucesso!
--- Results Clsutering for ['g1dg9qeh5m'] ---
classification
correct_unsafe     981
correct_bot        824
bot_pred_unsafe    176
unsafe_pred_bot     19
Name: count, dtype: int64

In [7]:
# df_result[df_result["classification"] == "unsafe_pred_bot"]["rule_id_list"].value_counts()

In [8]:
df_result["ua"] = df_result["headers"].apply(lambda x: x.get("user-agent") or x.get("User-Agent"))
df_result["x-moz"] = df_result["headers"].apply(lambda x: x.get("x-moz", {}) or x.get("X-moz", {}))

df_result[df_result["x-moz"] != {}]

Empty DataFrame
Columns: [datetime, decision, headers, ip, ip_api_isp, request, ua, filtered_headers, text_filtered, text, cluster, cluster_label, classification, x-moz]
Index: []

In [9]:
import pandas as pd

# 1. Lista para armazenar cada par (chave, valor) junto com seus rótulos
linhas_headers = []

# Iterar sobre o dataframe (usamos itertuples por ser mais rápido que iterrows)
for row in df_result.itertuples():
    headers = getattr(row, "headers", {})
    decision = getattr(row, "decision", "unknown")
    classification = getattr(row, "classification", "unknown")
    
    if isinstance(headers, dict):
        for k, v in headers.items():
            linhas_headers.append({
                "decision": decision,
                "classification": classification,
                "header_key": str(k).lower(), # Normalizar para minúsculo
                "header_value": str(v).strip()
            })

# 2. Criar um DataFrame "achatado"
df_flat = pd.DataFrame(linhas_headers)

# 3. Agrupar e contar as ocorrências
df_agrupado = (
    df_flat.groupby(["decision", "classification", "header_key", "header_value"])
    .size()
    .reset_index(name="contagem")
)

# Ordenar pelas maiores contagens
df_agrupado = df_agrupado.sort_values(by=["header_key", "contagem"], ascending=[True, False])

# ==============================================================================
# ANALISANDO OS HEADERS "SEC-FETCH"
# ==============================================================================

print("🔍 Filtrando apenas headers da família 'sec-fetch':")
# Filtra qualquer header que comece com "sec-fetch"
df_sec_fetch = df_agrupado[df_agrupado["header_key"].str.startswith("user")]

display(df_sec_fetch[df_sec_fetch["classification"] == "unsafe_pred_bot"])

# ==============================================================================
# BÔNUS: TABELA DINÂMICA (PIVOT) PARA ANÁLISE COMPARATIVA
# ==============================================================================
# Uma tabela dinâmica é a melhor forma de ver lado a lado como um valor 
# específico de sec-fetch se comportou nos erros e acertos.

print("\n📊 Tabela Dinâmica: Como os valores de sec-fetch se distribuem nas classificações:")

pivot_sec_fetch = pd.pivot_table(
    df_sec_fetch, 
    values="contagem", 
    index=["header_key", "header_value"], 
    columns=["decision", "classification"], 
    aggfunc="sum", 
    fill_value=0
)

display(pivot_sec_fetch)
pivot_sec_fetch_ordenada = pivot_sec_fetch.sort_values(
    by=("unsafe", "unsafe_pred_bot"), 
    ascending=False
)

# Exibir a tabela ordenada
display(pivot_sec_fetch_ordenada)

🔍 Filtrando apenas headers da família 'sec-fetch':

,decision,classification,header_key,header_value,contagem
27616,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 14; SM-A135M Build...,2
27610,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 11; SM-A305GT Buil...,1
27611,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 12; SM-A125M Build...,1
27612,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 12; SM-A325M Build...,1
27613,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 12; TECNO CH7n Bui...,1
27614,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 13; moto e13 Build...,1
27615,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 14; CPH2669 Build/...,1
27617,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 15; 24040RN64Y Bui...,1
27618,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 15; SM-S921B Build...,1
27619,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 15; moto g54 5G Bu...,1
27620,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 15; moto g54 5G Bu...,1
27621,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 15; moto g54 5G Bu...,1
27622,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 15; moto g54 5G Bu...,1
27623,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 15; moto g54 5G Bu...,1
27624,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 16; SM-A546E Build...,1
27625,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 16; SM-A546E Build...,1
27626,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 16; SM-A566E Build...,1
27627,unsafe,unsafe_pred_bot,user-agent,Mozilla/5.0 (Linux; Android 16; V2440 Build/BP...,1

📊 Tabela Dinâmica: Como os valores de sec-fetch se distribuem nas classificações:

decision                                                                  bot  \
classification                                                bot_pred_unsafe
header_key header_value
user-agent AdsBot-Google (+http://www.google.com/adsbot.html)               0
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...               0
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...               0
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...               0
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...               0
...                                                                       ...
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               1

decision                                                                   \
classification                                                correct_bot
header_key header_value
user-agent AdsBot-Google (+http://www.google.com/adsbot.html)          58
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...           1
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...          12
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...           1
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...           5
...                                                                   ...
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...           0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...           0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...           0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...           0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...           0

decision                                                              unsafe  \
classification                                                correct_unsafe
header_key header_value
user-agent AdsBot-Google (+http://www.google.com/adsbot.html)              0
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...              0
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...              0
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...              0
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...              0
...                                                                      ...
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...              1
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...              1
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...              1
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...              1
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...              0

decision
classification                                                unsafe_pred_bot
header_key header_value
user-agent AdsBot-Google (+http://www.google.com/adsbot.html)               0
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...               0
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...               0
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...               0
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...               0
...                                                                       ...
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               0

[1128 rows x 4 columns]

decision                                                                  bot  \
classification                                                bot_pred_unsafe
header_key header_value
user-agent Mozilla/5.0 (Linux; Android 14; SM-A135M Build/...               0
           Mozilla/5.0 (Linux; Android 12; SM-A125M Build/...               0
           Mozilla/5.0 (Linux; Android 12; TECNO CH7n Buil...               0
           Mozilla/5.0 (Linux; Android 11; SM-A305GT Build...               0
           Mozilla/5.0 (Linux; Android 14; CPH2669 Build/U...               0
...                                                                       ...
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               1
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...               0

decision                                                                   \
classification                                                correct_bot
header_key header_value
user-agent Mozilla/5.0 (Linux; Android 14; SM-A135M Build/...           0
           Mozilla/5.0 (Linux; Android 12; SM-A125M Build/...           0
           Mozilla/5.0 (Linux; Android 12; TECNO CH7n Buil...           0
           Mozilla/5.0 (Linux; Android 11; SM-A305GT Build...           0
           Mozilla/5.0 (Linux; Android 14; CPH2669 Build/U...           0
...                                                                   ...
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...           0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...           0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...           0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...           0
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...           1

decision                                                              unsafe  \
classification                                                correct_unsafe
header_key header_value
user-agent Mozilla/5.0 (Linux; Android 14; SM-A135M Build/...              0
           Mozilla/5.0 (Linux; Android 12; SM-A125M Build/...              0
           Mozilla/5.0 (Linux; Android 12; TECNO CH7n Buil...              0
           Mozilla/5.0 (Linux; Android 11; SM-A305GT Build...              0
           Mozilla/5.0 (Linux; Android 14; CPH2669 Build/U...              0
...                                                                      ...
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...              1
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...              1
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...              1
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...              0
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...              0

decision
classification                                                unsafe_pred_bot
header_key header_value
user-agent Mozilla/5.0 (Linux; Android 14; SM-A135M Build/...               2
           Mozilla/5.0 (Linux; Android 12; SM-A125M Build/...               1
           Mozilla/5.0 (Linux; Android 12; TECNO CH7n Buil...               1
           Mozilla/5.0 (Linux; Android 11; SM-A305GT Build...               1
           Mozilla/5.0 (Linux; Android 14; CPH2669 Build/U...               1
...                                                                       ...
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               0
           Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...               0
           Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...               0

[1128 rows x 4 columns]

In [10]:
import pandas as pd
from collections import Counter

# 1. Filtra apenas as requisições onde o modelo errou classificando Unsafe como Bot
df_erros = df_result[df_result["classification"] == "unsafe_pred_bot"]
total_erros = len(df_erros)

print(f"Total de requisições 'unsafe_pred_bot' analisadas: {total_erros}\n")

if total_erros > 0:
    # Contadores
    chaves_counter = Counter()
    pares_counter = Counter()

    # 2. Varre os headers desse grupo específico
    for headers in df_erros["headers"]:
        if isinstance(headers, dict):
            for k, v in headers.items():
                k_lower = str(k).lower()
                
                # Conta a presença da chave (ex: 'user-agent')
                chaves_counter[k_lower] += 1
                
                # Conta a presença do par exato (ex: 'user-agent': 'curl/7.68.0')
                pares_counter[(k_lower, str(v).strip())] += 1

    # =========================================================================
    # VISÃO 1: PRESENÇA DAS CHAVES (O Esqueleto da Requisição)
    # =========================================================================
    df_chaves = pd.DataFrame(chaves_counter.items(), columns=["Header", "Contagem"])
    df_chaves["Presença (%)"] = (df_chaves["Contagem"] / total_erros) * 100
    df_chaves = df_chaves.sort_values(by="Contagem", ascending=False).reset_index(drop=True)
    
    print("🕵️ 1. PRESENÇA DE HEADERS (O que compõe a estrutura dessas requisições?):")
    display(df_chaves.head(15))

    # =========================================================================
    # VISÃO 2: PARES CHAVE-VALOR MAIS COMUNS (A "Assinatura" do Ataque)
    # =========================================================================
    df_pares = pd.DataFrame(
        [{"Header": k, "Valor": v, "Contagem": c} for (k, v), c in pares_counter.items()]
    )
    df_pares["Frequência (%)"] = (df_pares["Contagem"] / total_erros) * 100
    df_pares = df_pares.sort_values(by="Contagem", ascending=False).reset_index(drop=True)
    
    print("\n🎯 2. VALORES MAIS COMUNS (Qual o disfarce exato que eles usam?):")
    display(df_pares.head(60))
    
else:
    print("Nenhuma amostra classificada como 'unsafe_pred_bot' foi encontrada no DataFrame.")

Total de requisições 'unsafe_pred_bot' analisadas: 19

🕵️ 1. PRESENÇA DE HEADERS (O que compõe a estrutura dessas requisições?):

                      Header  Contagem  Presença (%)
0                       host        19         100.0
1               x-request-id        19         100.0
2                  x-real-ip        19         100.0
3            x-forwarded-for        19         100.0
4           x-forwarded-host        19         100.0
5           x-forwarded-port        19         100.0
6          x-forwarded-proto        19         100.0
7         x-forwarded-scheme        19         100.0
8                   x-scheme        19         100.0
9   x-original-forwarded-for        19         100.0
10                 forwarded        19         100.0
11                   referer        19         100.0
12           accept-encoding        19         100.0
13                  priority        19         100.0
14                    cf-ray        19         100.0

🎯 2. VALORES MAIS COMUNS (Qual o disfarce exato que eles usam?):

,Header,Valor,Contagem,Frequência (%)
0,x-client-bot,false,19,100.000000
1,x-threat-score,0,19,100.000000
2,priority,"u=1, i",19,100.000000
3,x-body-pluginslength,1,19,100.000000
4,cf-ipcontinent,SA,19,100.000000
5,ip-api-proxy,0,19,100.000000
6,x-scheme,http,19,100.000000
7,ip-api-hosting,0,19,100.000000
8,x-http-version,HTTP/2,19,100.000000
9,x-body-vis,visible,19,100.000000
10,x-http-method,POST,19,100.000000
11,accept-encoding,"gzip, br",19,100.000000
12,x-http-tls-version,TLSv1.3,19,100.000000
13,x-forwarded-scheme,http,19,100.000000
14,x-forwarded-proto,http,19,100.000000
15,x-body-wd,false,19,100.000000
16,x-http-ssl-protocol,true,19,100.000000
17,x-forwarded-port,80,19,100.000000
18,x-forwarded-host,www.viveremforma.site,19,100.000000
19,sec-ch-ua-platform,"""Android""",19,100.000000
20,x-body-pdfviewerenabled,1,19,100.000000
21,sec-ch-ua,"""Not:A-Brand"";v=""99"", ""Android WebView"";v=""145...",19,100.000000
22,sec-ch-ua-mobile,?1,19,100.000000
23,accept,*/*,19,100.000000
24,origin,https://www.viveremforma.site,19,100.000000
25,sec-fetch-site,same-origin,19,100.000000
26,sec-fetch-mode,cors,19,100.000000
27,sec-fetch-dest,empty,19,100.000000
28,cdn-loop,cloudflare; loops=1,19,100.000000
29,host,www.viveremforma.site,19,100.000000
30,cf-ipcountry,BR,19,100.000000
31,cf-visitor,"{""scheme"":""https""}",19,100.000000
32,cf-cert-presented,false,19,100.000000
33,cf-cert-revoked,false,19,100.000000
34,cf-cert-verified,false,19,100.000000
35,x-body-hc,8,18,94.736842
36,x-body-touch,5,18,94.736842
37,x-body-lang,pt-BR,17,89.473684
38,x-body-langs,"pt-BR,en-US",17,89.473684
39,x-body-platform,Linux aarch64,17,89.473684
40,accept-language,"pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7",17,89.473684
41,ip-api-reverse,,14,73.684211
42,cf-timezone,America/Sao_Paulo,13,68.421053
43,x-body-suspres,0,12,63.157895
44,x-body-tz,America/Sao_Paulo,12,63.157895
45,x-body-dm,8,11,57.894737
46,x-requested-with,com.kwai.video,10,52.631579
47,x-body-dm,4,8,42.105263
48,x-body-suspres,1,7,36.842105
49,cf-region,São Paulo,6,31.578947
50,cf-region-code,SP,6,31.578947
51,x-body-tz,America/Fortaleza,5,26.315789
52,cf-timezone,America/Fortaleza,5,26.315789
53,cf-ipcity,São Paulo,5,26.315789
54,ip-api-region-name,são paulo,5,26.315789
55,cf-iplatitude,-23.54750,5,26.315789
56,cf-iplongitude,-46.63611,5,26.315789
57,cf-postal-code,01000-000,5,26.315789
58,pragma,no-cache,5,26.315789
59,cache-control,no-cache,5,26.315789

In [11]:
import pandas as pd

# 1. Definimos os headers suspeitos que queremos cruzar
chaves_alvo = ['x-body-tz', 'cf-timezone', 'cf-ipcity', 'ip-api-region-name']

linhas_combinadas = []

# 2. Extraímos apenas essas chaves de cada requisição
# Troque df_erros por df_result se quiser ver na base inteira
for headers in df_erros["headers"]:
    if isinstance(headers, dict):
        # Criamos um dicionário normalizando as chaves para minúsculo para facilitar a busca
        headers_lower = {str(k).lower(): str(v).strip() for k, v in headers.items()}
        
        # Pega o valor se existir, ou 'AUSENTE' se a requisição não tiver esse header
        linha = {
            chave: headers_lower.get(chave, "AUSENTE") 
            for chave in chaves_alvo
        }
        linhas_combinadas.append(linha)

# 3. Criamos um DataFrame com essas colunas
df_comb = pd.DataFrame(linhas_combinadas)

# 4. Agrupamos para ver exatamente as combinações que ocorrem juntas
combinacoes = (
    df_comb.value_counts()
    .reset_index(name="Quantidade")
)

print("🕵️ Cruzamento de Headers (Timezone vs Localização do IP):")
display(combinacoes)

🕵️ Cruzamento de Headers (Timezone vs Localização do IP):

,x-body-tz,cf-timezone,cf-ipcity,ip-api-region-name,Quantidade
0,America/Fortaleza,America/Fortaleza,Jacaraú,paraíba,4
1,America/Sao_Paulo,America/Sao_Paulo,Rio de Janeiro,rio de janeiro,2
2,America/Sao_Paulo,America/Sao_Paulo,São Paulo,são paulo,2
3,America/Manaus,America/Sao_Paulo,São Paulo,são paulo,2
4,America/Fortaleza,America/Fortaleza,Fortaleza,ceará,1
5,America/Sao_Paulo,America/Sao_Paulo,Vespasiano,minas gerais,1
6,America/Sao_Paulo,America/Recife,Recife,pernambuco,1
7,America/Sao_Paulo,America/Sao_Paulo,Viamão,rio grande do sul,1
8,America/Sao_Paulo,America/Sao_Paulo,Niterói,rio de janeiro,1
9,America/Sao_Paulo,America/Sao_Paulo,Serra,espírito santo,1
10,America/Sao_Paulo,America/Sao_Paulo,Guaratinguetá,são paulo,1
11,America/Sao_Paulo,America/Sao_Paulo,Quirinópolis,goiás,1
12,America/Sao_Paulo,America/Sao_Paulo,São Paulo,santa catarina,1

In [ ]:
tik_isp = pd.DataFrame()
tik_isp["ip_api_isp"] = df_result["ip_api_isp"]
tik_isp["classification"] = df_result["classification"]
tik_isp["ua"] = df_result["ua"]

In [ ]:

for nome_isp, contagem in tik_isp[tik_isp["classification"] == "unsafe_pred_bot"]["ip_api_isp"].value_counts().items():
      print(f"Provedor: {nome_isp} | Ocorrências: {contagem}")

Provedor:  | Ocorrências: 34
Provedor: Verizon Business | Ocorrências: 22
Provedor: Comcast Cable Communications, LLC | Ocorrências: 21
Provedor: T-Mobile USA, Inc. | Ocorrências: 19
Provedor: AT&T Enterprises, LLC | Ocorrências: 16
Provedor: Fastly, Inc. | Ocorrências: 15
Provedor: Charter Communications | Ocorrências: 9
Provedor: Cox Communications Inc. | Ocorrências: 7
Provedor: Frontier Communications Solutions | Ocorrências: 6
Provedor: Space Exploration Technologies Corporation | Ocorrências: 5
Provedor: Charter Communications Inc | Ocorrências: 4
Provedor: Charter Communications, Inc | Ocorrências: 4
Provedor: WideOpenWest Finance LLC | Ocorrências: 3
Provedor: Consolidated Communications, Inc. | Ocorrências: 3
Provedor: Hotwire Communications | Ocorrências: 3
Provedor: Comcast Cable Communications | Ocorrências: 3
Provedor: Frontier Communications Corporation | Ocorrências: 3
Provedor: PacketHub S.A. | Ocorrências: 2
Provedor: RCN | Ocorrências: 2
Provedor: Wyyerd Group | Ocorrências: 2
Provedor: Cable ONE | Ocorrências: 2
Provedor: iWiSP llc | Ocorrências: 1
Provedor: Metronet | Ocorrências: 1
Provedor: Mile High Networks, LLC | Ocorrências: 1
Provedor: Jackson County Rural Electric Membership Corporation | Ocorrências: 1
Provedor: Infinite Q Networks | Ocorrências: 1
Provedor: Siskiyou Telephone Company | Ocorrências: 1
Provedor: CableSouth Media III LLC | Ocorrências: 1
Provedor: CenturyLink Communications, LLC | Ocorrências: 1
Provedor: BAM Broadband Opco | Ocorrências: 1
Provedor: Charter Communications LLC | Ocorrências: 1
Provedor: Mikrotec Internet Services | Ocorrências: 1
Provedor: CABLE ONE, INC. | Ocorrências: 1
Provedor: Verizon Communications | Ocorrências: 1
Provedor: WTC Communications, Inc. | Ocorrências: 1
Provedor: Suddenlink Communications | Ocorrências: 1
Provedor: Oculus Networks Inc | Ocorrências: 1
Provedor: Western Iowa Networks | Ocorrências: 1
Provedor: ecoLINK | Ocorrências: 1
Provedor: Mediacom Communications Corp | Ocorrências: 1
Provedor: Nextlink Broadband | Ocorrências: 1
Provedor: Telecast Communications | Ocorrências: 1
Provedor: Blue Stream | Ocorrências: 1
Provedor: Wave Wireless LLC | Ocorrências: 1
Provedor: CenturyLink | Ocorrências: 1
Provedor: Beehive Broadband | Ocorrências: 1
Provedor: Hunter Communications | Ocorrências: 1
Provedor: TCT West, Inc. | Ocorrências: 1
Provedor: Vyve Broadband | Ocorrências: 1
Provedor: County Electric Power Association | Ocorrências: 1
Provedor: Brightspeed | Ocorrências: 1

In [ ]:
for nome_isp, contagem in tik_isp[tik_isp["classification"] == "unsafe_pred_bot"]["ua"].value_counts().items():
      print(f"{nome_isp} | Ocorrências: {contagem}")

Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Mobile Safari/537.36 | Ocorrências: 23
Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 | Ocorrências: 17
Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.3 Mobile/15E148 Safari/604.1 | Ocorrências: 16
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/29.0 Chrome/136.0.0.0 Mobile Safari/537.36 | Ocorrências: 16
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 | Ocorrências: 13
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.14 Safari/605.1.15 | Ocorrências: 7
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0 | Ocorrências: 6
Mozilla/5.0 (iPad; CPU OS 26_3_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/410.0.875971614 Mobile/15E148 Safari/604.1 | Ocorrências: 4
Mozilla/5.0 (iPad; CPU OS 26_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/145.0.7632.108 Mobile/15E148 Safari/604.1 | Ocorrências: 3
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) | Ocorrências: 3
Mozilla/5.0 (Linux; Android 9; KFTRWI) AppleWebKit/537.36 (KHTML, like Gecko) Silk/138.12.1 like Chrome/138.0.7204.244 Safari/537.36 | Ocorrências: 3
Mozilla/5.0 (iPad; CPU OS 26_3_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/145.0.7632.108 Mobile/15E148 Safari/604.1 | Ocorrências: 3
Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.3 Mobile/15E148 Safari/604.1 Ddg/26.3 | Ocorrências: 2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.3 Safari/605.1.15 | Ocorrências: 2
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Mobile Safari/537.36 EdgA/145.0.0.0 | Ocorrências: 2
Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Mobile/15E148 Safari/604.1 | Ocorrências: 2
Mozilla/5.0 (iPad; CPU OS 18_7_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/145.0.7632.108 Mobile/15E148 Safari/604.1 | Ocorrências: 2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.3 Safari/605.1.15 Ddg/26.3 | Ocorrências: 2
Mozilla/5.0 (Linux; Android 15; SM-S916U Build/AP3A.240905.015.A2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.120 Mobile Safari/537.36 newsbreak/26.6.4 | Ocorrências: 2
Mozilla/5.0 (Android 16; Mobile; rv:148.0) Gecko/148.0 Firefox/148.0 | Ocorrências: 2
Mozilla/5.0 (Linux; Android 9; KFTRPWI) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.7204.244 Safari/537.36 | Ocorrências: 2
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 | Ocorrências: 2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15 | Ocorrências: 2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15 | Ocorrências: 2
Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.4 Mobile/15E148 Safari/604.1 | Ocorrências: 1
Mozilla/5.0 (iPad; CPU OS 17_7_10 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/145.0.7632.108 Mobile/15E148 Safari/604.1 | Ocorrências: 1
Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.2 Mobile/15E148 Safari/604.1 | Ocorrências: 1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.2 Safari/605.1.15 | Ocorrências: 1
Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.7 Mobile/15E148 Safari/604.1 Ddg/18.7 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 16; SM-S921U Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.80 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (iPad; CPU OS 15_8_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.7 Mobile/15E148 Safari/604.1 | Ocorrências: 1
Mozilla/5.0 (iPad; CPU OS 26_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) EdgiOS/144.0.3719.115 Version/26.0 Mobile/15E148 Safari/604.1 | Ocorrências: 1
Mozilla/5.0 (iPhone; CPU iPhone OS 26_3_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) EdgiOS/143.0.3650.82 Version/26.0 Mobile/15E148 Safari/604.1 | Ocorrências: 1
Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.5 Mobile/15E148 Safari/604.1 | Ocorrências: 1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 9; KFONWI) AppleWebKit/537.36 (KHTML, like Gecko) Silk/138.12.1 like Chrome/138.0.7204.244 Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/24.0 Chrome/117.0.0.0 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 13; SM-A037U Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/143.0.7499.34 Mobile Safari/537.36 newsbreak/22.44.0 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 12; M8L 2022 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.120 Mobile Safari/537.36 AgentWeb/5.0.0  UCBrowser/11.6.4.950 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 11; SM-A037U Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 9; KFONWI Build/PS7331.4463N; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/138.0.7204.244 Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Safari/605.1.15 Ddg/18.7 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 16; SM-S721U Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.159 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 16; moto g - 2025 Build/W1VKS36H.9-12-2-1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.120 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (iPad; CPU OS 26_3_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) EdgiOS/144.0.3719.115 Version/26.0 Mobile/15E148 Safari/604.1 | Ocorrências: 1
Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Nextdoor v6.187.1 ndact:a5b3e08a-58a7-4493-9e19-896f5d48ee3f ndactsource:email | Ocorrências: 1
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 14; moto g play - 2024 Build/U1TFS34.100-35-14-1-12; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.120 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 15; SM-G996U Build/AP3A.240905.015.A2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.120 Mobile Safari/537.36 newsbreak/26.9.0 | Ocorrências: 1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.7 Safari/605.1.15 | Ocorrências: 1
Mozilla/5.0 (iPad; CPU OS 18_5_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/145.0.7632.108 Mobile/15E148 Safari/604.1 | Ocorrências: 1
Mozilla/5.0 (Linux; arm_64; Android 13; Infinix X6528B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.7103.111 YaBrowser/25.6.5.111.00 SA/3 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 11; KFSNWI) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.7559.228 Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 16; SM-A546U Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.120 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 12; SM-N970U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.120 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (iPad; CPU OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 16; SM-S731U Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.159 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (iPhone; CPU iPhone OS 18_7_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/22H218 Safari/604.1 [FBAN/FBIOS;FBAV/533.0.0.34.82;FBBV/799045545;FBDV/iPhone11,8;FBMD/iPhone;FBSN/iOS;FBSV/18.7.4;FBSS/2;FBID/phone;FBLC/en_US;FBOP/5;FBRV/805010445;IABMV/1] | Ocorrências: 1
Mozilla/5.0 (iPad; CPU OS 26_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/144.0.7559.85 Mobile/15E148 Safari/604.1 | Ocorrências: 1
Mozilla/5.0 (iPad; CPU OS 26_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/410.0.875971614 Mobile/15E148 Safari/604.1 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 16; SM-F936U Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.120 Mobile Safari/537.36 AgentWeb/5.0.0  UCBrowser/11.6.4.950 | Ocorrências: 1
Mozilla/5.0 (iPhone; CPU iPhone OS 26_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/23D127 Safari/604.1 [FBAN/FBIOS;FBAV/551.1.0.46.67;FBBV/899660416;FBDV/iPhone14,2;FBMD/iPhone;FBSN/iOS;FBSV/26.3;FBSS/3;FBID/phone;FBLC/en_US;FBOP/5;FBRV/0;IABMV/1] | Ocorrências: 1
Mozilla/5.0 (Linux; Android 16; SM-S906U Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.120 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 16; SM-S721U Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.122 Mobile Safari/537.36 AgentWeb/5.0.0  UCBrowser/11.6.4.950 | Ocorrências: 1
Mozilla/5.0 (iPad; CPU OS 26_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) EdgiOS/144.0.3719.115 Version/26.0 Mobile/15E148 Safari/604.1 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 9; KFMAWI) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.7204.244 Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 15; SM-S146VL Build/AP3A.240905.015.A2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.120 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.117 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (iPad; CPU OS 18_7_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/145.0.7632.108 Mobile/15E148 Safari/604.1 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 11; KFRAPWI) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.7559.228 Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 16; SM-S931U Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.120 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (iPhone; CPU iPhone OS 18_6_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/22G100 Safari/604.1 [FBAN/FBIOS;FBAV/550.0.0.34.65;FBBV/890804754;FBDV/iPhone14,5;FBMD/iPhone;FBSN/iOS;FBSV/18.6.2;FBSS/3;FBID/phone;FBLC/en_US;FBOP/5;FBRV/900736983;IABMV/1] | Ocorrências: 1
Mozilla/5.0 (Linux; Android 16; SM-A166U Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/143.0.7499.143 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/543.0.0.55.73;IABMV/1;] | Ocorrências: 1
Mozilla/5.0 (iPhone; CPU iPhone OS 26_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/145.0.7632.108 Mobile/15E148 Safari/604.1 | Ocorrências: 1
Mozilla/5.0 (X11; Linux x86_64; rv:148.0) Gecko/20100101 Firefox/148.0 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 16; SM-X210 Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.159 Safari/537.36 AgentWeb/5.0.0  UCBrowser/11.6.4.950 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 11; KFRAWI) AppleWebKit/537.36 (KHTML, like Gecko) Silk/144.3.1 like Chrome/144.0.7559.228 Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 16; Pixel 10 Build/BP4A.260205.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.120 Mobile Safari/537.36 newsbreak/26.9.1 | Ocorrências: 1
Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Pinterest/iOS | Ocorrências: 1
Mozilla/5.0 (Linux; Android 16; SM-S928U Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.120 Mobile Safari/537.36 newsbreaklite/24.44.0 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 16; SM-A356U Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.104 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/549.0.0.61.62;IABMV/1;] | Ocorrências: 1
Mozilla/5.0 (Linux; Android 16; SM-A546U Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.104 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/549.0.0.61.62;IABMV/1;] | Ocorrências: 1
Mozilla/5.0 (Linux; Android 14; A55 Build/U01005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.120 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 9; KFKAWI) AppleWebKit/537.36 (KHTML, like Gecko) Silk/138.12.1 like Chrome/138.0.7204.244 Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 14; moto g play - 2024 Build/U1TFS34.100-35-14-1-12; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.104 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/549.0.0.61.62;IABMV/1;] | Ocorrências: 1
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (iPad; CPU OS 15_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6,2 Mobile/15E148 Safari/604.1 | Ocorrências: 1
Mozilla/5.0 (iPhone; CPU iPhone OS 16_7_14 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/20H370 Safari/604.1 [FBAN/FBIOS;FBAV/551.1.0.46.67;FBBV/899660416;FBDV/iPhone10,2;FBMD/iPhone;FBSN/iOS;FBSV/16.7.14;FBSS/3;FBID/phone;FBLC/en_US;FBOP/5;FBRV/0;IABMV/1] | Ocorrências: 1
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (iPhone; CPU iPhone OS 16_7_12 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/20H364 Safari/604.1 [FBAN/FBIOS;FBAV/550.0.0.34.65;FBBV/890804754;FBDV/iPhone10,2;FBMD/iPhone;FBSN/iOS;FBSV/16.7.12;FBSS/3;FBID/phone;FBLC/en_US;FBOP/5;FBRV/900736983;IABMV/1] | Ocorrências: 1
Mozilla/5.0 (Linux; Android 16; SM-S918U Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.159 Mobile Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 9; KFONWI) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.7204.244 Safari/537.36 | Ocorrências: 1
Mozilla/5.0 (Linux; Android 11; KFSNWI) AppleWebKit/537.36 (KHTML, like Gecko) Silk/144.3.1 like Chrome/144.0.7559.228 Safari/537.36 | Ocorrências: 1

In [ ]:
for nome_isp, contagem in tik_isp[tik_isp["classification"] == "bot_pred_unsafe"]["ip_api_isp"].value_counts().items():
      print(f"Provedor: {nome_isp} | Ocorrências: {contagem}")

In [ ]:
for nome_isp, contagem in tik_isp[tik_isp["classification"] == "correct_unsafe"]["ip_api_isp"].value_counts().items():
      print(f"Provedor: {nome_isp} | Ocorrências: {contagem}")

Provedor: T-Mobile USA, Inc. | Ocorrências: 98
Provedor: Comcast Cable Communications, LLC | Ocorrências: 93
Provedor:  | Ocorrências: 79
Provedor: Verizon Business | Ocorrências: 71
Provedor: AT&T Enterprises, LLC | Ocorrências: 65
Provedor: Fastly, Inc. | Ocorrências: 59
Provedor: Charter Communications Inc | Ocorrências: 35
Provedor: Cox Communications Inc. | Ocorrências: 30
Provedor: Charter Communications | Ocorrências: 28
Provedor: Space Exploration Technologies Corporation | Ocorrências: 20
Provedor: Charter Communications, Inc | Ocorrências: 13
Provedor: Charter Communications LLC | Ocorrências: 12
Provedor: Verizon Communications | Ocorrências: 9
Provedor: Frontier Communications Solutions | Ocorrências: 8
Provedor: CenturyLink Communications, LLC | Ocorrências: 8
Provedor: Comcast Cable Communications | Ocorrências: 6
Provedor: Hotwire Communications | Ocorrências: 6
Provedor: Metronet | Ocorrências: 5
Provedor: Frontier Communications Corporation | Ocorrências: 5
Provedor: Spectrum | Ocorrências: 5
Provedor: CABLE ONE, INC. | Ocorrências: 5
Provedor: Buggs Island Telephone Co-operative | Ocorrências: 5
Provedor: CenturyLink | Ocorrências: 4
Provedor: Solarus | Ocorrências: 4
Provedor: Midcontinent Communications | Ocorrências: 4
Provedor: Wave Broadband | Ocorrências: 3
Provedor: Suddenlink Communications | Ocorrências: 3
Provedor: North State Telephone, LLC | Ocorrências: 3
Provedor: Plumas Sierra Telecommunications | Ocorrências: 3
Provedor: Cincinnati Bell Telephone Company LLC | Ocorrências: 3
Provedor: Blue Stream | Ocorrências: 2
Provedor: Harrisonville Telephone | Ocorrências: 2
Provedor: AT&T Enterprises | Ocorrências: 2
Provedor: PacketHub S.A. | Ocorrências: 2
Provedor: Brightspeed | Ocorrências: 2
Provedor: ViaSat, Inc. | Ocorrências: 2
Provedor: Empire Access | Ocorrências: 2
Provedor: TDS TELECOM | Ocorrências: 2
Provedor: RCN | Ocorrências: 2
Provedor: Wyyerd Group | Ocorrências: 2
Provedor: Akamai Technologies, Inc. | Ocorrências: 2
Provedor: WideOpenWest Finance LLC | Ocorrências: 2
Provedor: PenTeleData Inc. | Ocorrências: 2
Provedor: C Spire Fiber | Ocorrências: 2
Provedor: SpaceX Starlink | Ocorrências: 2
Provedor: Total Play Telecomunicaciones SA De CV | Ocorrências: 1
Provedor: United Electric Cooperative | Ocorrências: 1
Provedor: Drexel University | Ocorrências: 1
Provedor: Big River Telephone | Ocorrências: 1
Provedor: DataCamp Limited | Ocorrências: 1
Provedor: Central Utah Telephone | Ocorrências: 1
Provedor: Horry Telephone Cooperative, Inc. | Ocorrências: 1
Provedor: Paul Bunyan Communications | Ocorrências: 1
Provedor: Daystarr Communications | Ocorrências: 1
Provedor: Mikrotec Internet Services | Ocorrências: 1
Provedor: Wire 3 LLC | Ocorrências: 1
Provedor: Conexon Connect | Ocorrências: 1
Provedor: Arkwest Communications Inc | Ocorrências: 1
Provedor: Brantley Telephone Company, Inc. | Ocorrências: 1
Provedor: Breezeline | Ocorrências: 1
Provedor: JAB Wireless, INC. | Ocorrências: 1
Provedor: Dobson Fiber | Ocorrências: 1
Provedor: Everywhere Wireless, LLC | Ocorrências: 1
Provedor: WTC Communications, Inc. | Ocorrências: 1
Provedor: MPInet | Ocorrências: 1
Provedor: Coosa Valley Technologies Inc | Ocorrências: 1
Provedor: Datacamp Limited | Ocorrências: 1
Provedor: Kit Carson Electric Cooperative, Inc | Ocorrências: 1
Provedor: Anthem Broadband | Ocorrências: 1
Provedor: LocalTel Communications | Ocorrências: 1
Provedor: Pilot Fiber, Inc. | Ocorrências: 1
Provedor: Level 3 | Ocorrências: 1
Provedor: Pocketinet Communications, Inc | Ocorrências: 1
Provedor: Sonic.net, LLC | Ocorrências: 1
Provedor: Smith Bagley Inc | Ocorrências: 1
Provedor: MINET | Ocorrências: 1
Provedor: Zeta Broadband, Inc. | Ocorrências: 1
Provedor: Sjoberg's Inc | Ocorrências: 1
Provedor: Focus Broadband | Ocorrências: 1
Provedor: Horry Telephone Cooperative | Ocorrências: 1
Provedor: The Municipal Communications Utility of the City of Cedar Falls, Iowa | Ocorrências: 1
Provedor: Alyrica Networks Inc. | Ocorrências: 1
Provedor: AirFiber WISP LLC | Ocorrências: 1
Provedor: Syringa Networks, LLC | Ocorrências: 1
Provedor: LUMOS Networks, Inc. | Ocorrências: 1
Provedor: Consolidated Communications, Inc. | Ocorrências: 1
Provedor: Emery Telcom | Ocorrências: 1
Provedor: Sebastian | Ocorrências: 1
Provedor: empower, Delivered by Craighead Electric | Ocorrências: 1
Provedor: City of Chanute | Ocorrências: 1
Provedor: General Communication | Ocorrências: 1
Provedor: Strong Technology | Ocorrências: 1
Provedor: CityNet | Ocorrências: 1
Provedor: Boost Mobile | Ocorrências: 1
Provedor: IQ Fiber | Ocorrências: 1
Provedor: West Carolina Communications, LLC | Ocorrências: 1
Provedor: Ritter Communications | Ocorrências: 1
Provedor: Spanish Fork City | Ocorrências: 1
Provedor: Smithville Digital | Ocorrências: 1
Provedor: Antietam Broadband | Ocorrências: 1
Provedor: City and County of Denver | Ocorrências: 1
Provedor: Arvig Enterprises Inc. | Ocorrências: 1
Provedor: Farmers Telecommunications Cooperative | Ocorrências: 1
Provedor: GoSEMO Fiber | Ocorrências: 1
Provedor: FastTrack Communications Inc. | Ocorrências: 1
Provedor: Air Advantage LLC | Ocorrências: 1
Provedor: OPTICALTEL | Ocorrências: 1
Provedor: Greenlight Networks, LLC | Ocorrências: 1

In [ ]:
for nome_isp, contagem in tik_isp[tik_isp["classification"] == "correct_bot"]["ip_api_isp"].value_counts().items():
      print(f"Provedor: {nome_isp} | Ocorrências: {contagem}")

Provedor: Google LLC | Ocorrências: 244
Provedor: Cloudflare, Inc. | Ocorrências: 130
Provedor: Cablevision Systems Corp. | Ocorrências: 92
Provedor: T-Mobile USA, Inc. | Ocorrências: 65
Provedor:  | Ocorrências: 44
Provedor: Amazon.com, Inc. | Ocorrências: 44
Provedor: Comcast Cable Communications, LLC | Ocorrências: 38
Provedor: Verizon Business | Ocorrências: 38
Provedor: Windstream Communications LLC | Ocorrências: 34
Provedor: Wholesail networks LLC | Ocorrências: 26
Provedor: Google Fiber Inc. | Ocorrências: 20
Provedor: AT&T Enterprises, LLC | Ocorrências: 18
Provedor: Outbrain, Inc. | Ocorrências: 16
Provedor: Clouvider Limited | Ocorrências: 14
Provedor: Cogent Communications | Ocorrências: 11
Provedor: Datacamp Limited | Ocorrências: 11
Provedor: Cox Communications Inc. | Ocorrências: 11
Provedor: Amazon Technologies Inc. | Ocorrências: 11
Provedor: Amazon.com | Ocorrências: 11
Provedor: Limestone Networks, Inc. | Ocorrências: 9
Provedor: Optimum Online (Cablevision Systems) | Ocorrências: 7
Provedor: AT&T Enterprises | Ocorrências: 7
Provedor: Charter Communications, Inc | Ocorrências: 7
Provedor: Charter Communications | Ocorrências: 6
Provedor: DEFT.COM | Ocorrências: 5
Provedor: Charter Communications LLC | Ocorrências: 5
Provedor: DigitalOcean, LLC | Ocorrências: 4
Provedor: GTT Americas | Ocorrências: 4
Provedor: Hawaiian Telcom Services Company | Ocorrências: 4
Provedor: CenturyLink | Ocorrências: 4
Provedor: Telekom Slovenije d.d | Ocorrências: 3
Provedor: Willamette Valley Internet | Ocorrências: 3
Provedor: GTT Communications Inc. | Ocorrências: 3
Provedor: 123.Net, Inc. | Ocorrências: 3
Provedor: RCN | Ocorrências: 3
Provedor: Comcast Cable Communications | Ocorrências: 3
Provedor: CenturyLink Communications, LLC | Ocorrências: 3
Provedor: Web2Objects LLC | Ocorrências: 2
Provedor: Ipxo LLC | Ocorrências: 2
Provedor: Charter Communications Inc | Ocorrências: 2
Provedor: M247 Europe SRL | Ocorrências: 2
Provedor: HostPapa | Ocorrências: 2
Provedor: Surry Telephone Membership Corporation | Ocorrências: 2
Provedor: DataCamp Limited | Ocorrências: 2
Provedor: Jaguar Communications | Ocorrências: 2
Provedor: Space Exploration Technologies Corporation | Ocorrências: 2
Provedor: Static IP Services | Ocorrências: 2
Provedor: Frontier Communications Solutions | Ocorrências: 1
Provedor: A1 Slovenija | Ocorrências: 1
Provedor: Allo Communications LLC | Ocorrências: 1
Provedor: The Fusion Network, LLC | Ocorrências: 1
Provedor: LogicWeb Inc | Ocorrências: 1
Provedor: Interworks Networking Services | Ocorrências: 1
Provedor: WS Telecom Inc | Ocorrências: 1
Provedor: Wave Broadband | Ocorrências: 1
Provedor: Windstream Communications Inc | Ocorrências: 1
Provedor: Optyx Broadband Inc. | Ocorrências: 1
Provedor: UpCloud USA Inc | Ocorrências: 1
Provedor: WideOpenWest Finance LLC | Ocorrências: 1
Provedor: Cablevision Systems Corp | Ocorrências: 1
Provedor: Carnival Corporation | Ocorrências: 1
Provedor: Thunderbox Inc | Ocorrências: 1
Provedor: Midcontinent Communications | Ocorrências: 1
Provedor: Google Singapore Pte. Ltd. | Ocorrências: 1
Provedor: Shenandoah Cable Television LLC | Ocorrências: 1
Provedor: Hillsborough County Aviation Authority | Ocorrências: 1